spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zerobaseadmin
    password: zero!zero!

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update


server:
  port: 8081


feign:
  okhttp:
    enabled: true
  autoconfiguration:
    jackson:
      enabled: true

jwt:
  secret: secretKey

