spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mariadb://localhost:43306/cms?serverTimezone=UTC&characterEncoding=UTF-8
    driver: org.mariadb.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/user?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cmsuser
    password: cms

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  port: 8081


feign:
  okhttp:
    enabled: true

jwt:
  secret: secretKey

