spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://localhost:3306/order?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zerobaseadmin
    password: zero!zero!

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update

  redis:
    host: localhost
    port: 6379


server:
  port: 8082
  shutdown: graceful


feign:
  okhttp:
    enabled: true
  client:
    url:
      user-api: ec2-13-125-10-44.ap-northeast-2.compute.amazonaws.com:8081


jwt:
  secret: secretKey

