spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mariadb://localhost:43306/cmsorder?serverTimezone=UTC&characterEncoding=UTF-8
    driver: org.mariadb.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/order?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cmsorderuser
    password: cms

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  redis:
    host: localhost
    port: 6379


server:
  port: 8082
  shutdown: graceful


feign:
  okhttp:
    enabled: true

jwt:
  secret: secretKey

